name: coverage

on: [push]
env:
  RUST_BACKTRACE: full
jobs:
  coverage:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache tarpaulin
        uses: actions/cache@v2
        id: cache-tarpaulin
        with:
          path: ~/.cargo/bin/cargo-tarpaulin
          key: ${{ runner.os }}-tarpaulin-${{ hashFiles('**/Cargo.lock') }}

      - name: Install tarpaulin
        if: steps.cache-tarpaulin.outputs.cache-hit != 'true'
        run: cargo install cargo-tarpaulin

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --engine llvm --follow-exec --verbose --all-features --workspace --out xml --exclude-files tests/end-to-end.rs --coveralls ${{ secrets.COVERALLS_TOKEN }}

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
