name: coverage

on: [push]
env:
  RUST_BACKTRACE: full
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --engine llvm --follow-exec --verbose --all-features --workspace --out xml --exclude-files tests/end-to-end.rs

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
