name: tests

on: [push]
env:
  RUST_BACKTRACE: full
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      
      - name: Install nextest
        run: cargo install cargo-nextest

      - name: Spawn server in background
        run: |
          cargo run --release &

      - name: Run tests
        run: |
          cargo nextest run --release --no-fail-fast
          cargo nextest run --release --features=e2e-tests --no-fail-fast --test end-to-end --no-capture
