name: tests

on: [push]
env:
  RUST_BACKTRACE: full
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Spawn server in background
        run: |
          cargo run --release &

      - name: Run tests
        run: |
          cargo test --release --no-fail-fast -- --exact --show-output
          cargo test --release --features=e2e-tests --no-fail-fast --test end-to-end -- --exact --show-output --test-threads=1
